using System;
using System.Collections.Generic;

namespace ComCom_WebAPI.DataRO
{
    public partial class @SO1_01CODIGOCONTROL
    {
        public string Code { get; set; } = null!;
        public string U_SO1_CODIGOACTPRECI { get; set; } = null!;
        public string U_SO1_CODIGOACTPREDE { get; set; } = null!;
        public string U_SO1_CODIGOLOGAUTOR { get; set; } = null!;
        public string U_SO1_CODIGODINERO { get; set; } = null!;
        public string U_SO1_CODIGODINEROFP { get; set; } = null!;
        public string U_SO1_CODIGODINERODE { get; set; } = null!;
        public string U_SO1_CODIGOCORTECAJ { get; set; } = null!;
        public string U_SO1_CODIGOCORTECIE { get; set; } = null!;
        public string U_SO1_CODIGOCORTENOM { get; set; } = null!;
        public string U_SO1_CODIGODEPBANCA { get; set; } = null!;
        public string U_SO1_CODIGODEPBADET { get; set; } = null!;
        public string U_SO1_CODIGODINDEPTO { get; set; } = null!;
        public string U_SO1_CODIGOTRANSBAN { get; set; } = null!;
        public string U_SO1_CODIGODEVOLCOM { get; set; } = null!;
        public string U_SO1_CODIGODEVOLPAG { get; set; } = null!;
        public string U_SO1_CODIGODEVCOMDE { get; set; } = null!;
        public string U_SO1_CODIGONUMSERIE { get; set; } = null!;
        public string U_SO1_CODIGONUMLOTE { get; set; } = null!;
        public string U_SO1_CODIGOENTRMERC { get; set; } = null!;
        public string U_SO1_CODIGOENTMERDE { get; set; } = null!;
        public string U_SO1_CODIGOFACTURA { get; set; } = null!;
        public string U_SO1_CODIGONOTACRED { get; set; } = null!;
        public string U_SO1_CODIGOORDENCOM { get; set; } = null!;
        public string U_SO1_CODIGOORDCOMDE { get; set; } = null!;
        public string U_SO1_CODIGOSALIDAME { get; set; } = null!;
        public string U_SO1_CODIGOSALMEDET { get; set; } = null!;
        public string U_SO1_CODIGOVENTA { get; set; } = null!;
        public string U_SO1_CODIGOVENTADET { get; set; } = null!;
        public string U_SO1_CODIGOSUGCOMPRA { get; set; } = null!;
        public string U_SO1_CODIGOSUGCOMDET { get; set; } = null!;
        public string U_SO1_CODIGOTRASPASO { get; set; } = null!;
        public string U_SO1_CODIGOTRASPADET { get; set; } = null!;
        public string U_SO1_CODIGOCONTINVEN { get; set; } = null!;
        public string U_SO1_CODIGOCONTMUEBL { get; set; } = null!;
        public string U_SO1_CODIGOCONTINCRI { get; set; } = null!;
        public string U_SO1_CODIGOMUEBLE { get; set; } = null!;
        public string U_SO1_CODIGOMUEBLEART { get; set; } = null!;
        public string U_SO1_CODIGODEVOL { get; set; } = null!;
        public string U_SO1_CODIGODEVOLDET { get; set; } = null!;
        public string U_SO1_CODIGODEVOLGAS { get; set; } = null!;
        public string U_SO1_CODIGODEVOLRET { get; set; } = null!;
        public string U_SO1_CODIGOCOMPRA { get; set; } = null!;
        public string U_SO1_CODIGOCOMPRADET { get; set; } = null!;
        public string U_SO1_CODIGOCOBRANDET { get; set; } = null!;
        public string U_SO1_CODIGOVENCOBRO { get; set; } = null!;
        public string U_SO1_CODIGOVENRETIM { get; set; } = null!;
        public string U_SO1_CODIGOVENGASTAD { get; set; } = null!;
        public string U_SO1_CODIGOVENTAPERD { get; set; } = null!;
        public string U_SO1_CODIGOOPORVENTA { get; set; } = null!;
        public string U_SO1_CODIGOETAPAOPVE { get; set; } = null!;
        public string U_SO1_CODIGOOPOACTIVI { get; set; } = null!;
        public string U_SO1_CODIGOVENTATAE { get; set; } = null!;
        public string U_SO1_CODIGOVALEDESC { get; set; } = null!;
        public string U_SO1_CODIGOFECH { get; set; } = null!;
        public string U_SO1_CODIGOBITAPUNT { get; set; } = null!;
        public string U_SO1_CODIGOPAGOSERV { get; set; } = null!;
        public string U_SO1_CODIGOENTREGAD { get; set; } = null!;
        public string U_SO1_CODIGOENTDIDET { get; set; } = null!;
        public string U_SO1_CODIGOCERTREGA { get; set; } = null!;
        public string U_SO1_CODIGOARTIREST { get; set; } = null!;
        public string U_SO1_CODIGOARTRESAD { get; set; } = null!;
        public string U_SO1_01CODIGOACESME { get; set; } = null!;
        public string U_SO1_CODIGOPROPUNLP { get; set; } = null!;
        public string U_SO1_CODIGOBLOQMEMB { get; set; } = null!;
        public string U_SO1_CODIGOTRANSRPM { get; set; } = null!;
        public string U_SO1_CODIGOPAGOPROV { get; set; } = null!;
        public string U_SO1_CODIGOPAGPRDET { get; set; } = null!;
        public string U_SO1_CODIGOVENTAPRO { get; set; } = null!;
        public string U_SO1_CODIGOCANCECOB { get; set; } = null!;
        public string U_SO1_CODIGOCANCOBDT { get; set; } = null!;
        public string U_SO1_CODIGOMODIFVEN { get; set; } = null!;
        public string U_SO1_CODIGOVENTACOM { get; set; } = null!;
        public string U_SO1_MESASUC { get; set; } = null!;
        public string U_SO1_CODIGOCLIENESP { get; set; } = null!;
        public string U_SO1_CAMEXTACTIVA { get; set; } = null!;
        public string U_SO1_CAMEXTVALVAL { get; set; } = null!;
        public string U_SO1_CAMPOEXTRADEF { get; set; } = null!;
        public string U_SO1_VENTANTICIPO { get; set; } = null!;
        public string U_SO1_MONITOHIST { get; set; } = null!;
        public string U_SO1_MONITOHISTDET { get; set; } = null!;
    }
}
