import { IColumn } from "@fluentui/react";

export class ICatProved{
    constructor(
        public Ciudad: string,
        public CodEntProduccion: number,
        public Cod_Prov: number,
        public CodigoPostal: number,
        public Col: string,
        public Domicilio: string,
        public Email: string,
        public Estado: string,
        public FechUltPago: Date,
        public ImpoUltPago: number,
        public Nomb: string,
        public RegistroFederal: string,
        public Representante: string,
        public Tel: number,
        public TipMercado: string,
        public TipPersonaFiscal: string,
        public activo: boolean,
    ){}
}

export const provColumns: IColumn[] = [
    {   key: "CodigoEntidad",
        name: "Entidad de Producción",
        fieldName: "CodEntProduccion",
        minWidth: 100,
        maxWidth: 100,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
        onRender: (item: ICatProved) => {
            return item.CodEntProduccion;
        }
    },
    {   key: "CodigoProvedor",
        name: "Codigo Provedor",
        fieldName: "Cod_Prov",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
        onRender: (item: ICatProved) => {
            return item.Cod_Prov;
        }
    },
    {   key: "Nombre",
        name: "Nombre",
        fieldName: "Nomb",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "TipoPersona",
        name: "Tipo Persona",
        fieldName: "TipPersonaFiscal",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Representante",
        name: "Representante",
        fieldName: "Representante",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Email",
        name: "Email",
        fieldName: "Email",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Telefono",
        name: "Telefono",
        fieldName: "Tel",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Estado",
        name: "Estado",
        fieldName: "Estado",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Ciudad",
        name: "Ciudad",
        fieldName: "Ciudad",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Colonia",
        name: "Colonia",
        fieldName: "Col",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Domicilio",
        name: "Domicilio",
        fieldName: "Domicilio",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "CodigoPostal",
        name: "Codigo Postal",
        fieldName: "CodigoPostal",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "RegistroFederal",
        name: "RFC",
        fieldName: "RegistroFederal",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "TipoMercado",
        name: "Tipo de Mercado",
        fieldName: "TipMercado",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Activo",
        name: "Activo",
        fieldName: "Activo",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "FechaRegistro",
        name: "Fecha de ultimo pago",
        fieldName: "FechUltPago",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
    {   key: "Importe",
        name: "Importe de ultimo pago",
        fieldName: "ImpoUltPago",
        minWidth: 100,
        maxWidth: 200,
        isResizable: true,
        data: "string",
        isSorted: true,
        isSortedDescending: true,
        sortAscendingAriaLabel: "Sorted A to Z",
        sortDescendingAriaLabel: "Sorted Z to A",
    },
];
